### PR TITLE
added support to see if a hostname exists

### PR DESCRIPTION
**Pull request by jsloyer**
added support to check to see if a hostname exists.

API -> http://apidocs.cloudfoundry.org/214/routes/check_a_route_exists.html

### CODE REVIEW

**Comment by jsloyer** [comment]
Looks like an issue with pivotal for the unit tests...

**Comment by jabrena** [comment]
Hi @jsloyer, What is the difference between the method that you say and this query:

``` javascript
var filter = {
                    'q': 'host:' + appName + ';domain_guid:' + domain_guid,
                    'inline-relations-depth': 1
                };
                return CloudFoundryRoutes.getRoutes(filter);
``` 

You can see this example here:
https://github.com/IBM-Bluemix/cf-nodejs-client/blob/hostname-exists/test/lib/model/cloudcontroller/UploadStaticAppsTests.js#L100-L169

**Comment by jabrena** [comment]
Where is the TestCases about the new feature?

**Comment by jsloyer** [comment]
@jabrena It would be nice to have this method as its more straightforward then using that filter.  Thoughts?

**Comment by jabrena** [comment]
It is not a bad thing. Ok, but every new method requires a test case.

**Pull request closed without merging**
