### PR TITLE
Allow Query String Parameters for Events API

### PR DESCRIPTION
**Pull request by jthomas**
Events API allows for a query parameters that modify the results.
https://apidocs.cloudfoundry.org/223/events/list_all_events.html

Add optional parameter to *Events* model to allow for users to set the values.

### CODE REVIEW

**Comment by jabrena** [comment]
I have updated a bit the code.

Alk searches use a variable named: "Filter" 
To create, I am using the nomenclature: CONCEPT_options

In relation to events features from cloud controller, I think that CF has some performance problem because the time used to receive events is high. What is your opinion?

**Comment by jthomas** [comment]
Re-factoring looks good.

We do need to include the *useQuerystring: true* option on the request to allow for searching on events which match more than one filter (timestamp, type, actee). For example, finding events from an application and after a timestamp is allowed by sending the *q* parameter twice (once for each filter)[1]. Request module handles this automatically when a property value is an array and not a primitive value but only when the *useQuerystring* parameter is set to true.

Does that make sense? 

[1]https://apidocs.cloudfoundry.org/223/events/list_events_associated_with_an_app_since_january_1,_2014.html

**Comment by jthomas** [comment]
I've also seen extreme slowness from CF returning events which makes the tests a bit unstable. I have seen both tests successfully complete if the events API comes back correctly.

**Comment by jabrena** [comment]
Hi @jthomas, 

I added and example filtering by time:

``` js 
        var filter = {
            'q': 'timestamp>=' + "2015-10-16T00:00:00Z",
            'results-per-page': 20
        };
```
It runs without any change.

**Comment by jthomas** [comment]
If we want to run the following query, as per the command line:

cf curl "/v2/events?q=actee:eae34c72-c497-4461-b798-4ac3908db96c&q=timestamp>2015-11-09T18:00:00Z"

Without "useQueryString" set to true, we aren't able to use the filter to do this, array parameters get serialised incorrectly. We want to be able to do.... 
```
 var filter = {
   'q': ['timestamp>=' + "2015-10-16T00:00:00Z", 'actee:' + "SOME_APP_GUID"]
   'results-per-page': 20
};
```

**Comment by jabrena** [comment]
You have reason.
I have added the parameter that you say. You have reason :)
https://www.npmjs.com/package/request

Example1:

```` js
        var filter = {
            'q': ['timestamp>=' + "2015-10-16T00:00:00Z", 'actee:' + "7eddcf88-aba8-45e2-a682-0b6a00c8b93c"],
            'results-per-page': 20
        };
```

Example 2:

```
        var filter = {
            'q': ['timestamp>=' + "2015-10-16T00:00:00Z"],
            'results-per-page': 20
        }; 
```

Juan Antonio

**Comment by jthomas** [comment]
Thanks 💯

This is a great library by the way, nice work!

**Comment by jabrena** [comment]
Thx @jthomas

**Comment by jabrena** [comment]
Next week, I will release a new version (v0.11.0). If you are using some events feature the method will be events not getEvents. Besides I have moved login method from CloudController to UAA.

**Comment by jabrena** [comment]
Finally, the method continue with the same name.

**Comment by jthomas** [comment]
Thanks for letting me know, I'll fix my code!

**Pull request merged**
